steelrumors/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required as auth

from links.views import LinkListView
from links.views import UserProfileDetailView
from links.views import UserProfileEditView
from links.views import LinkCreateView
from links.views import LinkDetailView
from links.views import LinkUpdateView
from links.views import LinkDeleteView
from links.views import VoteFormView


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'steelrumors.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^$', LinkListView.as_view(), name='home'),

    url(r'^login/$', 'django.contrib.auth.views.login',
    	{'template_name': 'login.html'}, name='login'),

    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login',
    	name='logout'),

    url(r'^accounts/', include('registration.backends.simple.urls')),

    url(r'^users/(?P<slug>\w+)/$', UserProfileDetailView.as_view(),
        name='profile' ),

    url(r'^edit_profile/$', auth(UserProfileEditView.as_view()),
        name='edit_profile'),

    url(r'^link/create/$', auth(LinkCreateView.as_view()),
        name='link_create'),

    url(r'^link/(?P<pk>\d+)$', LinkDetailView.as_view(),
        name='link_detail'),

    url(r'^link/update/(?P<pk>\d+)$', auth(LinkUpdateView.as_view()),
        name='link_update'),

    url(r'^link/delete/(?P<pk>\d+)$', auth(LinkDeleteView.as_view()),
        name='link_delete'),

    url(r'^vote/$', auth(VoteFormView.as_view()), name='vote'),
)

links/models.py
from django.db import models
from django.db.models import Count
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse

class LinkVoteCountManager(models.Manager):
	def get_queryset(self):
		return super(LinkVoteCountManager, self).get_queryset().annotate(
			votes=Count('vote')).order_by('-votes')


class Link(models.Model):
	title = models.CharField('Headline', max_length=100)
	submitter = models.ForeignKey(User)
	submitted_on = models.DateTimeField(auto_now_add=True)
	rank_score = models.FloatField(default=0.0)
	url = models.URLField('URL', max_length=250, blank=True)
	description = models.TextField(blank=True)

	with_votes = LinkVoteCountManager()
	objects = models.Manager()

	def __unicode__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('link_detail', kwargs={'pk': str(self.id),})

class Vote(models.Model):
	voter = models.ForeignKey(User)
	link = models.ForeignKey(Link)

	def __unicode__(self):
		return "{0} voted for {1}".format(self.voter.username,
			self.link.title)

class UserProfile(models.Model):
	user = models.OneToOneField(User, unique=True)
	#Extra attributes here
	bio = models.TextField(null=True)

	def __unicode__(self):
		return "{0}'s profile".format(self.user)

def create_profile(sender, instance, created, **kwargs):
	''' A signal handler to ensure whenever a User is created, A UserProfile
	is created as well.
	'''
	if created:
		profile, created = UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_profile, sender=User)

links/forms.py
from django import forms
from .models import Link, Vote


class LinkForm(forms.ModelForm):
	class Meta:
		model = Link
		exclude = ('submitter', 'rank_score',)
class VoteForm(forms.ModelForm):
	class Meta:
		model = Vote

links/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import FormView
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse, reverse_lazy

from .forms import LinkForm, VoteForm
from .models import Link, Vote, UserProfile

class LinkListView(ListView):
	model = Link
	queryset = Link.with_votes.all()
	paginate_by = 5

	def get_context_data(self, **kwargs):
		context = super(LinkListView, self).get_context_data(**kwargs)
		if self.request.user.is_authenticated():
			voted = Vote.objects.filter(voter=self.request.user)
			links_in_page = [link.id for link in context['object_list']]
			voted = voted.filter(link__id__in=links_in_page)
			voted = voted.values_list('link_id', flat=True)
			context['voted'] = voted
		return context


class LinkDetailView(DetailView):
	model = Link


class LinkCreateView(CreateView):
	model = Link
	form_class = LinkForm

	def form_valid(self, form):
		f = form.save(commit=False)
		f.rank_score = 0.0
		f.submitter = self.request.user
		f.save()
		return super(LinkCreateView, self).form_valid(form)

class LinkUpdateView(UpdateView):
	model = Link
	form_class = LinkForm

class LinkDeleteView(DeleteView):
	model = Link
	success_url = reverse_lazy("home")

class UserProfileDetailView(DetailView):
	model = get_user_model()
	slug_field = 'username'
	template_name = "user_detail.html"

	def get_object(self, queryset=None):
		user = super(UserProfileDetailView, self).get_object(queryset)
		UserProfile.objects.get_or_create(user=user)
		return user

class UserProfileEditView(UpdateView):
	model = UserProfile
	template_name = 'edit_profile.html'
	fields = ['bio', ]

	def get_object(self, queryset=None):
		return UserProfile.objects.get_or_create(
			user=self.request.user)[0]

	def get_success_url(self):
		return reverse('profile', kwargs={'slug': self.request.user})


class JSONFormMixin(object):
	def create_response(self, vdict=dict(), valid_form=True):
		response = HttpResponse(json.dumps(vdict),
			content_type='application/json')
		response.status = 200 if valid_form else 500
		return response

class VoteFormBaseView(FormView):
	form_class = VoteForm

	def create_response(self, vdict=dict(), valid_form=True):
		response = HttpResponse(json.dumps(vdict))
		response.status = 200 if valid_form else 500
		return response


	def form_valid(self, form):
		link = get_object_or_404(Link, pk= form.data['link'])
		user = self.request.user
		prev_votes = Vote.objects.filter(voter=user, link=link)
		has_voted = (len(prev_votes) > 0)

		ret = {'success': 1}
		if not has_voted:
			#add vote
			v = Vote.objects.create(voter=user, link=link)
			ret['voteobj'] = v.id

		else:
			#delete vote
			prev_votes[0].delete()
			ret['unvoted'] = 1
		return self.create_response(ret, True)


	def form_invalid(self, form):
		ret = {'success': 0, 'form_errors': form.errors}
		return self.create_response(ret, False)


class VoteFormView(JSONFormMixin, VoteFormBaseView):
	pass

steelrumors/templates/base.html
<html>
<head>
  <title>Steel Rumors</title>
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/main.css" />
</head>
<body>
<h1>Steel Rumors</h1>

{% block content %}
{% endblock %}


{% block footer %}
<footer>
  <p>
    <a href="{% url 'home' %}">Home</a> |
{% if user.is_authenticated %}
	<a href="{% url 'link_create' %}">Submit a link</a>
    <a href="{% url 'logout' %}">Logout</a> |
    <a href="{% url 'profile' slug=user.username %}"><b>{{ user.username }}</b></a>
{% else %}
    <a href="{% url 'login' %}">Login</a> |
    <a href="{% url 'registration_register' %}">Register</a>
{% endif %}
  </p>
</footer>

{% endblock footer %}
</body>
</html>

steelrumors/templates/edit_profile.html
{% extends "base.html" %}

{% block content %}
<h2>{{ user.username }}'s Profile</h2>

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Edit">
</form>

{% endblock %}

steelrumors/templates/links/base.html
<html>
<head>
  <title>Steel Rumors</title>
  <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/main.css" />
  <script type="text/javascript" src="{{ STATIC_URL }}/js/jquery.min.js"></script>
  <script type="text/javascript" src="{{ STATIC_URL }}/js/vote.js"></script>
</head>
<body>
<h1>Steel Rumors</h1>

{% block content %}
{% endblock %}

{% block footer %}
<footer>
  <p>
    <a href="{% url 'home' %}">Home</a> |
{% if user.is_authenticated %}
	<a href="{% url 'link_create' %}">Submit a link</a>
    <a href="{% url 'logout' %}">Logout</a> |
    <a href="{% url 'profile' slug=user.username %}"><b>{{ user.username }}</b></a>
{% else %}
    <a href="{% url 'login' %}">Login</a> |
    <a href="{% url 'registration_register' %}">Register</a>
{% endif %}
  </p>
</footer>

{% endblock footer %}
</body>
</html>

steelrumors/templates/links/link_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<p>Are you sure you want to delete "{{ object.title }}"?</p>

<form method="post" action="{% url 'link_delete' pk=object.pk %}">
  {% csrf_token %}
  <a href="{% url 'link_detail' pk=object.pk %}">Go back</a> 
  <p><input type="submit" value="Confirm deletion" /></p>
</form> 

{% endblock %}

steelrumors/templates/links/link_detail.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
<style>
  #id_honeypot {
    display: none;
  }
</style>

<h2><a href="{{ object.link }}">{{ object.title }}</a></h2>
{% if object.submitter == user %}
  <a href="{% url 'link_update' pk=object.pk %}">Edit</a> | 
  <a href="{% url 'link_delete' pk=object.pk %}">Delete</a>
{% endif %}

<div class="desc">
  {{ object.description }}
</div>

<div class="comments">
  <h3>Comments</h3>

  <div class="comment_form">
{% if user.is_authenticated %}
  {% get_comment_form for object as form %}
  <form action="{% comment_form_target %}" method="POST">
    {% csrf_token %}
    {{ form.comment }}
    {{ form.honeypot }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="name" value="{{ user }}" />
    <input type="hidden" name="email" value="{{ user.email|default:'d@ummy.com' }}" />
    <input type="hidden" name="url" value="" />
    <input type="hidden" name="next" 
	   value="{% url 'link_detail' pk=object.id %}" />
    <input type="submit" value="Add comment" id="id_submit" />
  </form>
{% else %}
  <p>Please <a href="{% url 'login' %}">log in
  </a> to leave a comment.</p>
{% endif %}
  </div>


  {% render_comment_list for object %}
</div>


{% endblock %}

steelrumors/templates/links/link_form.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Add">
</form>
{% endblock %}

steelrumors/templates/links/link_list.html
{% extends 'links/base.html' %}
{% load comments %}

{% block content %}
{% if is_paginated %}
<ol start="{{ page_obj.start_index }}">
{% else %}
<ol>
{% endif %}
	{% for link in object_list %}
	<form method="POST" action="{% url 'vote' %}" class="vote_form">
	<li>[{{ link.votes }}]
	{% csrf_token %}
	<input type="hidden" id="id_link" name="link" class="hidden_id" value="{{ link.pk }}">

	<input type="hidden" id="id_voter" name="voter" class="hidden_id" value="{{ user.pk }}">

	{% if not user.authenticated %}
		<button disabled="Please Login to vote">+</button>
	{% elif link.pk not in voted %}
		<button>+</button>
	{% else %}
		<button>-</button>
	{% endif %}
		<a href="{% url 'link_detail' pk=link.pk %}">
		<b>{{ link.title }}</b>
		{% get_comment_count for link as comment_count %}
		{{ comment_count }} comment{{ comment_count|pluralize }}
		</a>
	</li>
	</form>
	{% endfor %}
</ol>
{% if is_paginated %}
<div class="pagination">
	{% if page_obj.has_next %}
	<a href="?page={{ page_obj.next_page_number }}">More &raquo;</a>
	{% endif %}
</div>
{% endif %}
{% endblock content %}

steelrumors/templates/login.html
{% extends "base.html" %}

{% block content %}
<h2>Login</h2>

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
  {% csrf_token %}
  <table>
    <tr>
      <td>{{ form.username.label_tag }}</td>
      <td>{{ form.username }}</td>
    </tr>
    <tr>
      <td>{{ form.password.label_tag }}</td>
      <td>{{ form.password }}</td>
    </tr>
  </table>
  
  <input type="submit" value="login" />
  <input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

steelrumors/templates/user_detail.html
{% extends "base.html" %}

{% block content %}
<h2>{{ object.username }}'s Profile</h2>
{% if object.userprofile.bio %}
<div>
<b>Bio:</b>
{{ object.userprofile.bio }}
</div>
{% endif %}
{% if object.username == user.username %}
<p><a href="{% url 'edit_profile' %}">Edit my profile</a></p>
{% endif %}

{% endblock %}